### Creare un dataframe con 4 colonne
<ul> 4 colonne
    <l>nomeCorso</l>
    <l>descrizione</l>
    <l>dataInizio</l>
    <l>dataFine</l>
</ul>

definisco il nome del dataframe (corso) poi definisco subito che lavoro su pandas (pd.) e che andrò a creare un dataframe(.DataFrame)

In [10]:
import pandas as pd

corsi = pd.DataFrame({
    "nomeCorso": ["Python", "SQL", "Excel","Power Query"],
    "descrizione": ["Base", "Intermedio", "Avanzato", "Base"],
    "dataInizio": ["2026-04-01", "2026-05-01", "2025-12-01", "2025-11-01"],
    "dataFine": ["2026-06-01", "2026-07-01", "2026-02-01", "2026-01-01"]
})

corso

     nomeCorso descrizione  dataInizio    dataFine
0       Python        Base  2026-04-01  2026-06-01
1          SQL  Intermedio  2026-05-01  2026-07-01
2        Excel    Avanzato  2025-12-01  2026-02-01
3  Power Query        Base  2025-11-01  2026-01-01

### Creare un dataframe con 5 colonne
<ul> 4 colonne
    <l>nome</l>
    <l>cognome</l>
    <l>dataNascita</l>
    <l>email</l>
    <l>telefono</l>
</ul>

In [21]:
import pandas as pd

studenti = pd.DataFrame({
    "nome": ["Michael", "Scott", "Tracy","Becky"],
    "cognome": ["Blu", "Rossi", "Verdi", "Bianchi"],
    "dataNascita": ["1992-06-25", "1993-07-27", "1994-08-28", "1995-09-29"],
    "email": ["mb@email.com", "sr@email.com", "tv@email.com", "bb@email.com"],
    "telefono": ["3456789000", "34576589900", "33785984783", "33467589939"]
})

studenti

      nome  cognome dataNascita         email     telefono
0  Michael      Blu  1992-06-25  mb@email.com   3456789000
1    Scott    Rossi  1993-07-27  sr@email.com  34576589900
2    Tracy    Verdi  1994-08-28  tv@email.com  33785984783
3    Becky  Bianchi  1995-09-29  bb@email.com  33467589939

PER SALVARE: to_csv è un metodo o una funzione che permette di salvare un dataframe in un file con formato .csv
index=false indica che non voglio stampare l'indice della lista

In [13]:
studenti.to_csv("studenti.csv", index=False) 
corsi.to_csv("corsi.csv", index=False)

installo la versione di Excel per poter salvare da Visual Studio Code in formato Excel

In [15]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [16]:
salva = corsi.to_excel("corsi_1.xlsx", index=False)
salva = studenti.to_excel("studenti_1.xlsx", index=False)

In [ ]:
salva = corsi.to_excel("corsi_1.xlsx", index=False)
if salva is None:
    print("Il salvataggio del file è andato a buon fine")
else:
    print("Attenzione: si è verificato un errore durante il salvataggio del file")

Il salvataggio del file è andato a buon fine

In [18]:
salva = studenti.to_excel("corsi_1.xlsx", index=False)
if salva is None:
    print("Il salvataggio del file è andato a buon fine")
else:
    print("Attenzione: si è verificato un errore durante il salvataggio del file")

Il salvataggio del file è andato a buon fine